[package]
name = "cart_lin"
version = "0.1.0"
edition = "2024"
description = "Conversion between cartesian and linear indices"
readme = "README.md"
license  = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
nalgebra = "0.32"
ndarray = "0.16"